---
name: Continuous integration

on:

  pull_request:
    branches:
      - main
    paths:
      - src/**
      - package.json
      - pnpm-lock.yaml
      - tsconfig.json
      - test/**
      - eslint.config.mjs
      - api-extractor.json
      - .readme.md
      - .github/workflows/ci.yml
  push:
    paths:
      - src/**
      - package.json
      - pnpm-lock.yaml
      - tsconfig.json
      - test/**
      - eslint.config.mjs
      - api-extractor.json
      - .readme.md
      - .github/workflows/ci.yml

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  issues: write
  pull-requests: write
  checks: write

jobs:
  build:
    permissions:
      actions: read
      contents: read
    uses: ./.github/workflows/compile-package.yml
    secrets: inherit

  lint:
    needs:
      - build
    permissions:
      actions: read
      contents: read
      issues: write
      pull-requests: write
      statuses: write
    uses: ./.github/workflows/lint-package.yml
    secrets: inherit

  test:
    needs:
      - build
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
    uses: IT-Service-NPM/.github/.github/workflows/test-package.yml@main
    secrets: inherit

  npmJS:
    needs:
      - build
      - test
    environment: npm
    runs-on: ubuntu-latest
    permissions:
      actions: read
      deployments: write
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:

    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - uses: IT-Service-NPM/.github/.github/actions/setup@main
      with:
        node-version: "24.x"

    - uses: IT-Service-NPM/.github/.github/actions/download-package-dist@main

    - name: Update API documentation
      shell: bash
      run: pnpm run --if-present build:readme:API

    - name: Update readme.md
      shell: bash
      run: pnpm run --if-present build:readme

    - uses: codfish/semantic-release-action@v4
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GIT_AUTHOR_NAME: "github-actions-shell"
        GIT_AUTHOR_EMAIL: "github-actions[bot]@users.noreply.github.com"
        GIT_COMMITTER_NAME: "github-actions-shell"
        GIT_COMMITTER_EMAIL: "github-actions[bot]@users.noreply.github.com"
