---
name: Compile 'dist' from sources

on:

  workflow_dispatch:

  workflow_call:

jobs:
  build:
    permissions:
      actions: read
      contents: read
    uses: IT-Service-NPM/.github/.github/workflows/compile-package.yml@main
    secrets: inherit
